
import { Exercise, MuscleGroup, MovementPattern, AvailableEquipment } from '../types';

export const EXERCISE_LIBRARY: Exercise[] = [
  // ===== SQUAT PATTERN =====
  {
    id: 'back_squat',
    name: 'Back Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Brace core', 'Break at hips and knees simultaneously', 'Drive knees out', 'Chest up'],
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    primaryMuscles: [MuscleGroup.QUADS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Elbows high', 'Upright torso', 'Push knees forward over toes'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hold weight at chest', 'Sit between heels', 'Elbows inside knees at bottom'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Feet shoulder width', 'Lower until 90° knee bend', 'Don\'t lock knees at top'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Rear foot elevated', 'Vertical shin on front leg', 'Control the descent'],
  },
  {
    id: 'overhead_squat',
    name: 'Overhead Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Wide grip', 'Active shoulders', 'Bar stays over mid-foot'],
  },

  // ===== HINGE PATTERN =====
  {
    id: 'conventional_deadlift',
    name: 'Conventional Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CORE, MuscleGroup.FOREARMS, MuscleGroup.TRAPS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hips hinge back', 'Bar stays close to body', 'Lock out with glutes', 'Neutral spine'],
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Wide stance, toes out', 'Push floor apart', 'Hips close to bar'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Slight knee bend', 'Push hips back', 'Feel hamstring stretch', 'Bar slides down thighs'],
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap Bar Deadlift',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.TRAPS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.SPECIALTY_BAR],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Step inside bar', 'Grip handles at center', 'Push floor away'],
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Bar on upper back', 'Hinge at hips', 'Slight knee bend', 'Feel hamstring stretch'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    primaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hike pass between legs', 'Violent hip snap', 'Arms are ropes', 'Squeeze glutes at top'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Upper back on bench', 'Drive through heels', 'Squeeze glutes at top', 'Chin tucked'],
  },

  // ===== HORIZONTAL PUSH =====
  {
    id: 'bench_press',
    name: 'Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Retract shoulder blades', 'Arch back slightly', 'Bar path: nipple line to lockout', 'Leg drive'],
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['30-45° incline', 'Retract scapula', 'Lower to upper chest'],
  },
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    primaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Hands shoulder-width', 'Elbows tucked', 'Lower to lower chest'],
  },
  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Squeeze shoulder blades', 'Control the descent', 'Press and slightly converge at top'],
  },
  {
    id: 'pushup',
    name: 'Push-Up',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Rigid plank position', 'Elbows at 45°', 'Full range of motion'],
  },
  {
    id: 'dip',
    name: 'Dip',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Lean forward for chest emphasis', 'Stay upright for tricep emphasis', 'Control descent'],
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Slight bend in elbows', 'Squeeze at the center', 'Control the eccentric'],
  },

  // ===== HORIZONTAL PULL =====
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hinge to ~45°', 'Pull to lower chest/upper stomach', 'Squeeze shoulder blades'],
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Torso parallel to floor', 'Dead stop each rep', 'Explosive pull'],
  },
  {
    id: 'db_row',
    name: 'Dumbbell Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hand and knee on bench', 'Row to hip', 'Squeeze at top'],
  },
  {
    id: 'cable_row',
    name: 'Seated Cable Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Chest tall', 'Pull to lower sternum', 'Don\'t lean back excessively'],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    primaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.CABLE, AvailableEquipment.BANDS],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Pull to forehead', 'Externally rotate at end', 'Squeeze rear delts'],
  },

  // ===== VERTICAL PUSH =====
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Brace core tight', 'Press bar in front of face', 'Push head through at lockout'],
  },
  {
    id: 'push_press',
    name: 'Push Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.QUADS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Quick dip and drive', 'Use leg power to initiate', 'Lock out overhead'],
  },
  {
    id: 'db_overhead_press',
    name: 'Dumbbell Overhead Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Start at shoulder height', 'Press straight up', 'Control the descent'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRAPS],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Slight bend in elbows', 'Raise to shoulder height', 'Lead with elbows not hands'],
  },

  // ===== VERTICAL PULL =====
  {
    id: 'pull_up',
    name: 'Pull-Up',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Overhand grip, wider than shoulders', 'Pull chest to bar', 'Engage lats'],
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    primaryMuscles: [MuscleGroup.BACK, MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Underhand grip, shoulder width', 'Pull chin over bar', 'Full extension at bottom'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.CABLE, AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Wide grip', 'Pull to upper chest', 'Lean back slightly', 'Squeeze lats'],
  },

  // ===== CARRY =====
  {
    id: 'farmers_carry',
    name: 'Farmer\'s Carry',
    primaryMuscles: [MuscleGroup.CORE, MuscleGroup.TRAPS, MuscleGroup.FOREARMS],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    movementPattern: MovementPattern.CARRY,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Tall posture', 'Shoulders packed down', 'Brace core', 'Short quick steps'],
  },

  // ===== CORE =====
  {
    id: 'plank',
    name: 'Plank',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Rigid body line', 'Squeeze glutes', 'Breathe normally'],
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Dead hang', 'Raise legs to parallel or higher', 'Control the descent'],
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Brace hard', 'Extend slowly', 'Don\'t let hips sag'],
  },

  // ===== ISOLATION =====
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Elbows pinned at sides', 'Full range of motion', 'Don\'t swing'],
  },
  {
    id: 'db_curl',
    name: 'Dumbbell Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Alternate or both arms', 'Supinate at the top', 'Control the negative'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Neutral grip', 'Elbows pinned', 'Full range of motion'],
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Elbows pinned at sides', 'Full extension', 'Squeeze at bottom'],
  },
  {
    id: 'overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Keep elbows close to head', 'Full stretch at bottom', 'Lock out at top'],
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Lower to forehead', 'Keep elbows stationary', 'EZ bar preferred'],
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    primaryMuscles: [MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full range of motion', 'Squeeze at peak contraction', 'Control the eccentric'],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    primaryMuscles: [MuscleGroup.QUADS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full extension', 'Squeeze quads at top', 'Don\'t use momentum'],
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    primaryMuscles: [MuscleGroup.CALVES],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE, AvailableEquipment.BODYWEIGHT, AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full stretch at bottom', 'Pause at top', 'Even foot pressure'],
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.BACK],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Hinge forward', 'Lead with elbows', 'Squeeze shoulder blades'],
  },
  {
    id: 'shrug',
    name: 'Barbell Shrug',
    primaryMuscles: [MuscleGroup.TRAPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Straight up, not rolling', 'Hold at top briefly', 'Heavy loads okay'],
  },
  {
    id: 'wrist_curl',
    name: 'Wrist Curl',
    primaryMuscles: [MuscleGroup.FOREARMS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Forearms on bench', 'Full range of motion', 'Both directions'],
  },
];

/**
 * Look up an exercise by ID.
 */
export const getExerciseById = (id: string): Exercise | undefined => {
  return EXERCISE_LIBRARY.find(e => e.id === id);
};

/**
 * Filter exercises by available equipment.
 */
export const filterByEquipment = (equipment: AvailableEquipment[]): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.equipment.some(eq => equipment.includes(eq)));
};

/**
 * Filter exercises by movement pattern.
 */
export const filterByMovementPattern = (pattern: MovementPattern): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.movementPattern === pattern);
};

/**
 * Filter exercises by muscle group (primary).
 */
export const filterByMuscleGroup = (muscle: MuscleGroup): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.primaryMuscles.includes(muscle));
};

/**
 * Get a numbered list of exercises for the AI prompt.
 */
export const getExerciseListForPrompt = (): string => {
  return EXERCISE_LIBRARY.map((e, i) =>
    `${i + 1}. ${e.name} (${e.id}) — ${e.movementPattern}, ${e.primaryMuscles.join('/')}, Equipment: ${e.equipment.join('/')}, ${e.isCompound ? 'Compound' : 'Isolation'}, Difficulty: ${e.difficulty}`
  ).join('\n');
};
