
import { Exercise, MuscleGroup, MovementPattern, AvailableEquipment } from '../types';

export const EXERCISE_LIBRARY: Exercise[] = [
  // ===== SQUAT PATTERN =====
    {
      id: 'high_bar_squat',
      name: 'High Bar Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
      secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Bar high on traps', 'Upright torso', 'Knees forward'],
    },
    {
      id: 'low_bar_squat',
      name: 'Low Bar Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
      secondaryMuscles: [MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Bar low on rear delts', 'Hip drive', 'Lean forward slightly'],
    },
    {
      id: 'pause_squat',
      name: 'Pause Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
      secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Pause at bottom', 'Stay tight', 'Explode up'],
    },
    {
      id: 'tempo_squat',
      name: 'Tempo Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
      secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Slow eccentric', 'Controlled movement', 'Explode concentrically'],
    },
    {
      id: 'safety_bar_squat',
      name: 'Safety Bar Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
      secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.SPECIALTY_BAR],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Use safety bar', 'Upright torso', 'Drive through midfoot'],
    },
    {
      id: 'box_squat',
      name: 'Box Squat',
      primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
      secondaryMuscles: [MuscleGroup.CORE],
      movementPattern: MovementPattern.SQUAT,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Sit back to box', 'Pause briefly', 'Explode up'],
    },
    // ===== BENCH PATTERN =====
    {
      id: 'pause_bench',
      name: 'Pause Bench Press',
      primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.TRICEPS],
      secondaryMuscles: [MuscleGroup.SHOULDERS],
      movementPattern: MovementPattern.HORIZONTAL_PUSH,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'intermediate',
      isCompound: true,
      cues: ['Pause on chest', 'Stay tight', 'Explode up'],
    },
    // ===== PRESS PATTERN =====
    {
      id: 'seated_dumbbell_press',
      name: 'Seated Dumbbell Press',
      primaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.TRICEPS],
      secondaryMuscles: [MuscleGroup.CORE],
      movementPattern: MovementPattern.VERTICAL_PUSH,
      equipment: [AvailableEquipment.DUMBBELL],
      difficulty: 'beginner',
      isCompound: true,
      cues: ['Sit upright', 'Press dumbbells overhead', 'Control down'],
    },
    // ===== DEADLIFT/HINGE VARIATIONS (already present, but can add more if needed) =====
    {
      id: 'deficit_deadlift',
      name: 'Deficit Deadlift',
      primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
      secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CORE],
      movementPattern: MovementPattern.HINGE,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'advanced',
      isCompound: true,
      cues: ['Stand on plate', 'Greater range of motion', 'Drive from floor'],
    },
    {
      id: 'snatch_grip_deadlift',
      name: 'Snatch Grip Deadlift',
      primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
      secondaryMuscles: [MuscleGroup.TRAPS, MuscleGroup.CORE],
      movementPattern: MovementPattern.HINGE,
      equipment: [AvailableEquipment.BARBELL],
      difficulty: 'advanced',
      isCompound: true,
      cues: ['Wide grip', 'Shoulders over bar', 'Drive through heels'],
    },
  {
    id: 'back_squat',
    name: 'Back Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Brace core', 'Break at hips and knees simultaneously', 'Drive knees out', 'Chest up'],
  },
  {
    id: 'front_squat',
    name: 'Front Squat',
    primaryMuscles: [MuscleGroup.QUADS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Elbows high', 'Upright torso', 'Push knees forward over toes'],
  },
  {
    id: 'goblet_squat',
    name: 'Goblet Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hold weight at chest', 'Sit between heels', 'Elbows inside knees at bottom'],
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Feet shoulder width', 'Lower until 90° knee bend', 'Don\'t lock knees at top'],
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Rear foot elevated', 'Vertical shin on front leg', 'Control the descent'],
  },
  {
    id: 'overhead_squat',
    name: 'Overhead Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Wide grip', 'Active shoulders', 'Bar stays over mid-foot'],
  },
  {
    id: 'pin_squat',
    name: 'Pin Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Set pins at sticking point', 'Dead start each rep', 'Drive explosively off pins'],
  },
  {
    id: 'anderson_squat',
    name: 'Anderson Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Start from bottom position on pins', 'No stretch reflex', 'Reset between reps'],
  },
  {
    id: 'zercher_squat',
    name: 'Zercher Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.BICEPS, MuscleGroup.BACK],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Bar in elbow crooks', 'Stay upright', 'Great for front-loaded strength'],
  },
  {
    id: 'belt_squat',
    name: 'Belt Squat',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Load through hips not spine', 'No spinal compression', 'Great for back-off volume'],
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    primaryMuscles: [MuscleGroup.QUADS],
    secondaryMuscles: [MuscleGroup.GLUTES],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Shoulder pads engaged', 'Full depth', 'Drive through whole foot'],
  },
  {
    id: 'walking_lunge',
    name: 'Walking Lunge',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.BARBELL, AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Long stride', 'Knee over ankle', 'Upright torso', 'Control each step'],
  },
  {
    id: 'reverse_lunge',
    name: 'Reverse Lunge',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.BARBELL, AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Step back', 'Front shin vertical', 'Drive through front heel'],
  },
  {
    id: 'step_up',
    name: 'Step-Up',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.SQUAT,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.BARBELL, AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Box at knee height', 'Drive through lead leg only', 'Don\'t push off trailing foot'],
  },

  // ===== HINGE PATTERN =====
  {
    id: 'conventional_deadlift',
    name: 'Conventional Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CORE, MuscleGroup.FOREARMS, MuscleGroup.TRAPS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hips hinge back', 'Bar stays close to body', 'Lock out with glutes', 'Neutral spine'],
  },
  {
    id: 'sumo_deadlift',
    name: 'Sumo Deadlift',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Wide stance, toes out', 'Push floor apart', 'Hips close to bar'],
  },
  {
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Slight knee bend', 'Push hips back', 'Feel hamstring stretch', 'Bar slides down thighs'],
  },
  {
    id: 'trap_bar_deadlift',
    name: 'Trap Bar Deadlift',
    primaryMuscles: [MuscleGroup.QUADS, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE, MuscleGroup.TRAPS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.SPECIALTY_BAR],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Step inside bar', 'Grip handles at center', 'Push floor away'],
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Bar on upper back', 'Hinge at hips', 'Slight knee bend', 'Feel hamstring stretch'],
  },
  {
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    primaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hike pass between legs', 'Violent hip snap', 'Arms are ropes', 'Squeeze glutes at top'],
  },
  {
    id: 'hip_thrust',
    name: 'Hip Thrust',
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Upper back on bench', 'Drive through heels', 'Squeeze glutes at top', 'Chin tucked'],
  },
  {
    id: 'pause_deadlift',
    name: 'Pause Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Pause at knee height', 'Maintain back angle', 'Stay tight through pause'],
  },
  {
    id: 'tempo_deadlift',
    name: 'Tempo Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.QUADS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Slow controlled eccentric', '3-5 second lowering', 'Maintain position throughout'],
  },
  {
    id: 'block_pull',
    name: 'Block Pull (Rack Pull)',
    primaryMuscles: [MuscleGroup.BACK, MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.TRAPS, MuscleGroup.CORE, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Bar elevated on blocks/pins', 'Overload lockout', 'Drive hips through'],
  },
  {
    id: 'stiff_leg_deadlift',
    name: 'Stiff-Leg Deadlift',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.BACK, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Legs nearly straight', 'Hinge from hips', 'Deeper stretch than RDL'],
  },
  {
    id: 'single_leg_rdl',
    name: 'Single-Leg RDL',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Hinge on one leg', 'Back leg extends behind', 'Square hips', 'Touch weight to mid-shin'],
  },
  {
    id: 'nordic_curl',
    name: 'Nordic Hamstring Curl',
    primaryMuscles: [MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'advanced',
    isCompound: false,
    cues: ['Kneel with feet anchored', 'Lower slowly under control', 'Catch with hands if needed'],
  },
  {
    id: 'cable_pull_through',
    name: 'Cable Pull-Through',
    primaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.CORE],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Face away from cable', 'Hinge at hips', 'Squeeze glutes to stand', 'Great hinge teacher'],
  },
  {
    id: 'reverse_hyper',
    name: 'Reverse Hyperextension',
    primaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [MuscleGroup.BACK],
    movementPattern: MovementPattern.HINGE,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Torso on pad', 'Swing legs up using glutes', 'Controlled tempo', 'Decompresses spine'],
  },

  // ===== HORIZONTAL PUSH =====
  {
    id: 'bench_press',
    name: 'Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Retract shoulder blades', 'Arch back slightly', 'Bar path: nipple line to lockout', 'Leg drive'],
  },
  {
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['30-45° incline', 'Retract scapula', 'Lower to upper chest'],
  },
  {
    id: 'close_grip_bench',
    name: 'Close-Grip Bench Press',
    primaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Hands shoulder-width', 'Elbows tucked', 'Lower to lower chest'],
  },
  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Squeeze shoulder blades', 'Control the descent', 'Press and slightly converge at top'],
  },
  {
    id: 'pushup',
    name: 'Push-Up',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Rigid plank position', 'Elbows at 45°', 'Full range of motion'],
  },
  {
    id: 'dip',
    name: 'Dip',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Lean forward for chest emphasis', 'Stay upright for tricep emphasis', 'Control descent'],
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Slight bend in elbows', 'Squeeze at the center', 'Control the eccentric'],
  },
  {
    id: 'tempo_bench',
    name: 'Tempo Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['3-5 second eccentric', 'Controlled descent', 'Maintain tightness', 'Explode concentrically'],
  },
  {
    id: 'floor_press',
    name: 'Floor Press',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Lie on floor', 'Elbows touch floor each rep', 'Eliminates leg drive', 'Great for lockout strength'],
  },
  {
    id: 'spoto_press',
    name: 'Spoto Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Pause 1-2 inches off chest', 'Hold for 1-2 seconds', 'Do not touch chest', 'Builds bottom-end strength'],
  },
  {
    id: 'larsen_press',
    name: 'Larsen Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Legs straight and elevated', 'No leg drive', 'Increases upper body demand', 'Stay tight on bench'],
  },
  {
    id: 'decline_bench',
    name: 'Decline Bench Press',
    primaryMuscles: [MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['15-30° decline', 'Lower to lower chest', 'Control the bar path'],
  },
  {
    id: 'incline_db_press',
    name: 'Incline Dumbbell Press',
    primaryMuscles: [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['30-45° incline', 'Press up and slightly inward', 'Deep stretch at bottom'],
  },

  // ===== HORIZONTAL PULL =====
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hinge to ~45°', 'Pull to lower chest/upper stomach', 'Squeeze shoulder blades'],
  },
  {
    id: 'pendlay_row',
    name: 'Pendlay Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Torso parallel to floor', 'Dead stop each rep', 'Explosive pull'],
  },
  {
    id: 'db_row',
    name: 'Dumbbell Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Hand and knee on bench', 'Row to hip', 'Squeeze at top'],
  },
  {
    id: 'cable_row',
    name: 'Seated Cable Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Chest tall', 'Pull to lower sternum', 'Don\'t lean back excessively'],
  },
  {
    id: 'face_pull',
    name: 'Face Pull',
    primaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.CABLE, AvailableEquipment.BANDS],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Pull to forehead', 'Externally rotate at end', 'Squeeze rear delts'],
  },
  {
    id: 't_bar_row',
    name: 'T-Bar Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Straddle the bar', 'Pull to chest', 'Squeeze shoulder blades', 'Chest supported or bent-over'],
  },
  {
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Chest on incline bench', 'Eliminates momentum', 'Row to hip line', 'Squeeze at top'],
  },
  {
    id: 'meadows_row',
    name: 'Meadows Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Landmine setup', 'Staggered stance', 'Overhand grip on bar end', 'Row to hip'],
  },
  {
    id: 'seal_row',
    name: 'Seal Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Lie face-down on elevated bench', 'Arms hang freely', 'Pure back contraction', 'No momentum'],
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.HORIZONTAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT, AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Body straight like plank', 'Pull chest to bar', 'Squeeze shoulder blades'],
  },

  // ===== VERTICAL PUSH =====
  {
    id: 'overhead_press',
    name: 'Overhead Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Brace core tight', 'Press bar in front of face', 'Push head through at lockout'],
  },
  {
    id: 'push_press',
    name: 'Push Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.QUADS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Quick dip and drive', 'Use leg power to initiate', 'Lock out overhead'],
  },
  {
    id: 'db_overhead_press',
    name: 'Dumbbell Overhead Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Start at shoulder height', 'Press straight up', 'Control the descent'],
  },
  {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRAPS],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Slight bend in elbows', 'Raise to shoulder height', 'Lead with elbows not hands'],
  },
  {
    id: 'z_press',
    name: 'Z-Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Seated on floor, legs straight', 'No back support', 'Pure overhead strength', 'Demands core stability'],
  },
  {
    id: 'arnold_press',
    name: 'Arnold Press',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRICEPS],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Start palms facing you', 'Rotate as you press', 'Full overhead lockout'],
  },
  {
    id: 'landmine_press',
    name: 'Landmine Press',
    primaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.CHEST],
    secondaryMuscles: [MuscleGroup.TRICEPS, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PUSH,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Bar in landmine attachment', 'Press at an angle', 'Great for shoulder health', 'Single or double arm'],
  },

  // ===== VERTICAL PULL =====
  {
    id: 'pull_up',
    name: 'Pull-Up',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Overhand grip, wider than shoulders', 'Pull chest to bar', 'Engage lats'],
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    primaryMuscles: [MuscleGroup.BACK, MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Underhand grip, shoulder width', 'Pull chin over bar', 'Full extension at bottom'],
  },
  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.CABLE, AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Wide grip', 'Pull to upper chest', 'Lean back slightly', 'Squeeze lats'],
  },
  {
    id: 'weighted_pull_up',
    name: 'Weighted Pull-Up',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Dip belt or weight vest', 'Full dead hang', 'Chin over bar', 'Control descent'],
  },
  {
    id: 'neutral_grip_pull_up',
    name: 'Neutral-Grip Pull-Up',
    primaryMuscles: [MuscleGroup.BACK, MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Palms facing each other', 'Shoulder-friendly grip', 'Full range of motion'],
  },
  {
    id: 'close_grip_pulldown',
    name: 'Close-Grip Pulldown',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.BICEPS],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['V-bar or close neutral grip', 'Pull to upper chest', 'Emphasizes lower lats'],
  },
  {
    id: 'cable_pullover',
    name: 'Cable Pullover',
    primaryMuscles: [MuscleGroup.BACK],
    secondaryMuscles: [MuscleGroup.CHEST, MuscleGroup.CORE],
    movementPattern: MovementPattern.VERTICAL_PULL,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Stand facing cable', 'Straight arms pull down', 'Feel lat stretch overhead', 'Squeeze at bottom'],
  },

  // ===== CARRY =====
  {
    id: 'farmers_carry',
    name: 'Farmer\'s Carry',
    primaryMuscles: [MuscleGroup.CORE, MuscleGroup.TRAPS, MuscleGroup.FOREARMS],
    secondaryMuscles: [MuscleGroup.SHOULDERS, MuscleGroup.GLUTES],
    movementPattern: MovementPattern.CARRY,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['Tall posture', 'Shoulders packed down', 'Brace core', 'Short quick steps'],
  },
  {
    id: 'suitcase_carry',
    name: 'Suitcase Carry',
    primaryMuscles: [MuscleGroup.CORE, MuscleGroup.FOREARMS],
    secondaryMuscles: [MuscleGroup.TRAPS, MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CARRY,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'beginner',
    isCompound: true,
    cues: ['One arm only', 'Don\'t lean to loaded side', 'Anti-lateral flexion', 'Great for obliques'],
  },
  {
    id: 'overhead_carry',
    name: 'Overhead Carry',
    primaryMuscles: [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.TRAPS],
    movementPattern: MovementPattern.CARRY,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.KETTLEBELL],
    difficulty: 'intermediate',
    isCompound: true,
    cues: ['Lock arm overhead', 'Ribs down', 'Brace hard', 'Slow controlled steps'],
  },

  // ===== CORE =====
  {
    id: 'plank',
    name: 'Plank',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Rigid body line', 'Squeeze glutes', 'Breathe normally'],
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Dead hang', 'Raise legs to parallel or higher', 'Control the descent'],
  },
  {
    id: 'ab_wheel',
    name: 'Ab Wheel Rollout',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Brace hard', 'Extend slowly', 'Don\'t let hips sag'],
  },
  {
    id: 'pallof_press',
    name: 'Pallof Press',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.CABLE, AvailableEquipment.BANDS],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Stand perpendicular to cable', 'Press hands straight out', 'Resist rotation', 'Anti-rotation exercise'],
  },
  {
    id: 'cable_woodchop',
    name: 'Cable Woodchop',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [MuscleGroup.SHOULDERS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Rotate through core', 'Arms guide the path', 'High-to-low or low-to-high', 'Control the movement'],
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Lie on back', 'Opposite arm and leg extend', 'Low back pressed to floor', 'Breathe out on extension'],
  },
  {
    id: 'copenhagen_plank',
    name: 'Copenhagen Plank',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Side plank with top leg on bench', 'Adductor and core demand', 'Keep body straight', 'Great for groin health'],
  },
  {
    id: 'turkish_getup',
    name: 'Turkish Get-Up',
    primaryMuscles: [MuscleGroup.CORE, MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.GLUTES, MuscleGroup.QUADS],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.KETTLEBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'advanced',
    isCompound: true,
    cues: ['Lie to standing with weight overhead', 'Slow and deliberate', 'Eyes on weight', 'Full body integration'],
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    primaryMuscles: [MuscleGroup.CORE],
    secondaryMuscles: [],
    movementPattern: MovementPattern.CORE,
    equipment: [AvailableEquipment.BODYWEIGHT],
    difficulty: 'advanced',
    isCompound: false,
    cues: ['Grip bench behind head', 'Rigid body lever', 'Lower slowly', 'Only shoulder blades touch'],
  },

  // ===== ISOLATION =====
  {
    id: 'barbell_curl',
    name: 'Barbell Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Elbows pinned at sides', 'Full range of motion', 'Don\'t swing'],
  },
  {
    id: 'db_curl',
    name: 'Dumbbell Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Alternate or both arms', 'Supinate at the top', 'Control the negative'],
  },
  {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primaryMuscles: [MuscleGroup.BICEPS, MuscleGroup.FOREARMS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Neutral grip', 'Elbows pinned', 'Full range of motion'],
  },
  {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Elbows pinned at sides', 'Full extension', 'Squeeze at bottom'],
  },
  {
    id: 'overhead_tricep_ext',
    name: 'Overhead Tricep Extension',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Keep elbows close to head', 'Full stretch at bottom', 'Lock out at top'],
  },
  {
    id: 'skull_crusher',
    name: 'Skull Crusher',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'intermediate',
    isCompound: false,
    cues: ['Lower to forehead', 'Keep elbows stationary', 'EZ bar preferred'],
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl',
    primaryMuscles: [MuscleGroup.HAMSTRINGS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full range of motion', 'Squeeze at peak contraction', 'Control the eccentric'],
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    primaryMuscles: [MuscleGroup.QUADS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full extension', 'Squeeze quads at top', 'Don\'t use momentum'],
  },
  {
    id: 'calf_raise',
    name: 'Calf Raise',
    primaryMuscles: [MuscleGroup.CALVES],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE, AvailableEquipment.BODYWEIGHT, AvailableEquipment.BARBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Full stretch at bottom', 'Pause at top', 'Even foot pressure'],
  },
  {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primaryMuscles: [MuscleGroup.SHOULDERS],
    secondaryMuscles: [MuscleGroup.BACK],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL, AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Hinge forward', 'Lead with elbows', 'Squeeze shoulder blades'],
  },
  {
    id: 'shrug',
    name: 'Barbell Shrug',
    primaryMuscles: [MuscleGroup.TRAPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Straight up, not rolling', 'Hold at top briefly', 'Heavy loads okay'],
  },
  {
    id: 'wrist_curl',
    name: 'Wrist Curl',
    primaryMuscles: [MuscleGroup.FOREARMS],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Forearms on bench', 'Full range of motion', 'Both directions'],
  },
  {
    id: 'preacher_curl',
    name: 'Preacher Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL, AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Armpits on pad', 'Full extension', 'No swinging', 'EZ bar or dumbbells'],
  },
  {
    id: 'incline_db_curl',
    name: 'Incline Dumbbell Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.DUMBBELL],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['45° incline bench', 'Arms hang straight down', 'Greater long-head stretch', 'No swinging'],
  },
  {
    id: 'cable_curl',
    name: 'Cable Curl',
    primaryMuscles: [MuscleGroup.BICEPS],
    secondaryMuscles: [MuscleGroup.FOREARMS],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.CABLE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Constant tension', 'Elbows pinned', 'Straight bar or EZ attachment'],
  },
  {
    id: 'jm_press',
    name: 'JM Press',
    primaryMuscles: [MuscleGroup.TRICEPS],
    secondaryMuscles: [MuscleGroup.CHEST],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.BARBELL],
    difficulty: 'advanced',
    isCompound: false,
    cues: ['Hybrid skull crusher / close-grip bench', 'Bar comes to chin/throat area', 'Elbows flare slightly', 'Powerlifting tricep builder'],
  },
  {
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    primaryMuscles: [MuscleGroup.CALVES],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Targets soleus', 'Full stretch at bottom', 'Pause at top', 'Slow eccentric for growth'],
  },
  {
    id: 'hip_adductor',
    name: 'Hip Adductor',
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Squeeze inner thighs', 'Control the eccentric', 'Don\'t use momentum'],
  },
  {
    id: 'hip_abductor',
    name: 'Hip Abductor',
    primaryMuscles: [MuscleGroup.GLUTES],
    secondaryMuscles: [],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE, AvailableEquipment.BANDS],
    difficulty: 'beginner',
    isCompound: false,
    cues: ['Push knees outward', 'Targets glute medius', 'Good for hip stability'],
  },
  {
    id: 'glute_ham_raise',
    name: 'Glute-Ham Raise',
    primaryMuscles: [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
    secondaryMuscles: [MuscleGroup.CORE],
    movementPattern: MovementPattern.ISOLATION,
    equipment: [AvailableEquipment.MACHINE],
    difficulty: 'advanced',
    isCompound: false,
    cues: ['GHD machine', 'Lower with control', 'Hamstrings do the work', 'Elite posterior chain builder'],
  },
];

/**
 * Get all exercises.
 */
export const getAllExercises = (): Exercise[] => {
  return EXERCISE_LIBRARY;
};

/**
 * Look up an exercise by ID.
 */
export const getExerciseById = (id: string): Exercise | undefined => {
  return EXERCISE_LIBRARY.find(e => e.id === id);
};

/**
 * Filter exercises by available equipment.
 */
export const filterByEquipment = (equipment: AvailableEquipment[]): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.equipment.some(eq => equipment.includes(eq)));
};

/**
 * Filter exercises by movement pattern.
 */
export const filterByMovementPattern = (pattern: MovementPattern): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.movementPattern === pattern);
};

/**
 * Filter exercises by muscle group (primary).
 */
export const filterByMuscleGroup = (muscle: MuscleGroup): Exercise[] => {
  return EXERCISE_LIBRARY.filter(e => e.primaryMuscles.includes(muscle));
};

/**
 * Get a numbered list of exercises for the AI prompt.
 */
export const getExerciseListForPrompt = (): string => {
  return EXERCISE_LIBRARY.map((e, i) =>
    `${i + 1}. ${e.name} (${e.id}) — ${e.movementPattern}, ${e.primaryMuscles.join('/')}, Equipment: ${e.equipment.join('/')}, ${e.isCompound ? 'Compound' : 'Isolation'}, Difficulty: ${e.difficulty}`
  ).join('\n');
};
